Lumeer/engine

api/src/main/java/io/lumeer/engine/api/data/DataStorageDialect.java, mongodb-storage/src/main/java/io/lumeer/mongodb/MongoDbStorageDialect.java, war/pom.xml, war/src/main/java/io/lumeer/engine/controller/DocumentFacade.java, war/src/main/java/io/lumeer/engine/controller/LinkingFacade.java, war/src/main/java/io/lumeer/engine/controller/VersionFacade.java, war/src/main/java/io/lumeer/engine/controller/configuration/ConfigurationManipulator.java, war/src/main/java/io/lumeer/engine/hints/ValueTypeHint.java, war/src/main/java/io/lumeer/engine/push/PushNotifications.java, war/src/main/java/io/lumeer/engine/push/PushService.java, war/src/main/java/io/lumeer/engine/rest/ViewService.java
These changes ensure that no code from `mongodb-storage` can be used in `war` module.
=> Use mongodb-storage as runtime dependency

war/src/main/java/io/lumeer/engine/controller/DocumentFacade.java, war/src/main/java/io/lumeer/engine/controller/VersionFacade.java, war/src/main/java/io/lumeer/engine/rest/CollectionService.java, war/src/test/java/io/lumeer/engine/controller/VersionFacadeIntegrationTest.java
Minor changes in `VersionFacade` and places where it is injected.
=> Refactor VersionFacade

api/src/main/java/io/lumeer/engine/api/data/DataFilter.java, api/src/main/java/io/lumeer/engine/api/data/DataStorage.java, api/src/main/java/io/lumeer/engine/api/data/DataStorageDialect.java, mongodb-storage/src/main/java/io/lumeer/mongodb/MongoDbDataFilter.java, mongodb-storage/src/main/java/io/lumeer/mongodb/MongoDbStorage.java, mongodb-storage/src/main/java/io/lumeer/mongodb/MongoDbStorageDialect.java, mongodb-storage/src/test/java/io/lumeer/mongodb/MongoDbStorageTest.java, war/src/main/java/io/lumeer/engine/controller/DocumentFacade.java, war/src/main/java/io/lumeer/engine/controller/ProjectFacade.java, war/src/main/java/io/lumeer/engine/controller/SearchFacade.java, war/src/main/java/io/lumeer/engine/controller/SecurityFacade.java, war/src/main/java/io/lumeer/engine/controller/VersionFacade.java, war/src/main/java/io/lumeer/engine/controller/configuration/ConfigurationManipulator.java, war/src/main/java/io/lumeer/engine/rest/CollectionService.java, war/src/test/java/io/lumeer/engine/controller/CollectionMetadataFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/controller/ProjectFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/controller/SecurityFacadeIntegrationTest.java
Please do not merge yet, just trying to run the tests...
=> Data filters instead of string conversion

war/src/main/java/io/lumeer/engine/controller/CollectionFacade.java, war/src/main/java/io/lumeer/engine/controller/CollectionMetadataFacade.java, war/src/main/java/io/lumeer/engine/controller/DocumentFacade.java
Metadata are updated each time document is created or updated, or collection metadata is changed.
=> Track last time collection was used and list of recently used documents

api/src/main/java/io/lumeer/engine/api/data/DataSort.java, api/src/main/java/io/lumeer/engine/api/data/DataStorage.java, api/src/main/java/io/lumeer/engine/api/data/DataStorageDialect.java, mongodb-storage/src/main/java/io/lumeer/mongodb/MongoDbDataSort.java, mongodb-storage/src/main/java/io/lumeer/mongodb/MongoDbStorage.java, mongodb-storage/src/main/java/io/lumeer/mongodb/MongoDbStorageDialect.java, war/src/main/java/io/lumeer/engine/controller/CollectionFacade.java, war/src/main/java/io/lumeer/engine/controller/SearchFacade.java, war/src/main/java/io/lumeer/engine/rest/CollectionService.java
Added DataSort class that supports sorting the way DataFilter supports filtering.
=> introduced DataSort class

api/src/main/java/io/lumeer/engine/api/exception/UserAlreadyExistsException.java, war/src/main/java/io/lumeer/engine/controller/DatabaseInitializer.java, war/src/main/java/io/lumeer/engine/controller/ProjectFacade.java, war/src/main/java/io/lumeer/engine/util/ErrorMessageBuilder.java, war/src/test/java/io/lumeer/engine/controller/ProjectFacadeIntegrationTest.java
Add check for user uniqueness and refactor tests in case of potentional bug when methods are executed concurrently.
I forgot to append Issue number, so here it is: LMR121 (for merge).
=> Add user check to ProjectFacade and refactor its test

war/src/main/java/io/lumeer/engine/controller/ConfigurationFacade.java, war/src/main/java/io/lumeer/engine/controller/configuration/ConfigurationManipulator.java, war/src/test/java/io/lumeer/engine/controller/ConfigurationFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/controller/configuration/ConfigurationManipulatorIntegrationTest.java
You can find the configuration entry structure [on wiki](https://github.com/Lumeer/engine/wiki/Metadata-Structure#configurationfacade).
When merging this, do not squash the commits so it can easily be seen what changes are made in refactoring and which resolves LMR-130.
=> Enable restricted flag in configuration #LMR-130

api/pom.xml, api/src/main/java/io/lumeer/engine/api/constraint/CaseConstraintType.java, api/src/main/java/io/lumeer/engine/api/constraint/Coders.java, api/src/main/java/io/lumeer/engine/api/constraint/Constraint.java, api/src/main/java/io/lumeer/engine/api/constraint/ConstraintManager.java, api/src/main/java/io/lumeer/engine/api/constraint/DateTimeConstraintType.java, api/src/main/java/io/lumeer/engine/api/constraint/FixingFunctionConstraint.java, api/src/main/java/io/lumeer/engine/api/constraint/FunctionConstraint.java, api/src/main/java/io/lumeer/engine/api/constraint/ListConstraintType.java, api/src/main/java/io/lumeer/engine/api/constraint/MatchesConstraintType.java, api/src/main/java/io/lumeer/engine/api/constraint/NumberConstraintType.java, api/src/main/java/io/lumeer/engine/api/exception/InvalidValueException.java, api/src/test/java/io/lumeer/engine/api/constraint/ConstraintManagerTest.java, api/src/test/resources/log4j2.xml, mongodb-storage/src/main/java/io/lumeer/mongodb/MongoDbStorage.java, mongodb-storage/src/main/java/io/lumeer/mongodb/codecs/BigDecimalCodec.java, war/src/main/java/io/lumeer/engine/controller/CollectionMetadataFacade.java, war/src/main/java/io/lumeer/engine/controller/DocumentFacade.java, war/src/main/java/io/lumeer/engine/rest/DocumentService.java, war/src/main/java/io/lumeer/engine/util/ExceptionMapper.java, war/src/test/java/io/lumeer/engine/controller/CollectionMetadataFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/rest/DocumentServiceIntegrationTest.java
It is not top notch, there are non-trivial code duplicates, but given the limited time I planned to spent here, I believe we are good to go.
=> Finished constraints #LMR-35

api/src/main/java/io/lumeer/engine/api/exception/OrganizationAlreadyExistsException.java, war/src/main/java/io/lumeer/engine/controller/OrganizationFacade.java, war/src/main/java/io/lumeer/engine/rest/OrganizationService.java, war/src/main/java/io/lumeer/engine/util/ErrorMessageBuilder.java, war/src/test/java/io/lumeer/engine/controller/OrganizationFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/rest/OrganizationServiceIntegrationTest.java
Matej actually implemented almost everything. I changed REST URL paths, did some minor changes and corrected errors, and also added tests and javadoc. 
What needs to be done is to check rights and roles when doing operations, but to do that, we firstly need to redesign SecurityFacade.
=> OrganizationService

api/pom.xml, api/src/main/java/io/lumeer/engine/api/dto/Organization.java, api/src/main/java/io/lumeer/engine/api/dto/Project.java, war/src/main/java/io/lumeer/engine/controller/DatabaseInitializer.java, war/src/main/java/io/lumeer/engine/controller/OrganizationFacade.java, war/src/main/java/io/lumeer/engine/controller/ProjectFacade.java, war/src/main/java/io/lumeer/engine/rest/OrganizationService.java, war/src/main/java/io/lumeer/engine/rest/ProjectService.java, war/src/test/java/io/lumeer/engine/controller/ConfigurationFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/controller/LinkingFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/controller/OrganizationFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/controller/ProjectFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/controller/SecurityFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/controller/UserGroupFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/rest/GroupServiceIntegrationTest.java, war/src/test/java/io/lumeer/engine/rest/OrganizationServiceIntegrationTest.java, war/src/test/java/io/lumeer/engine/rest/ProjectServiceIntegrationTest.java, war/src/test/java/io/lumeer/engine/rest/UserServiceIntegrationTest.java
I added new dependency to project api, so don't forget to make `mvn clean install` in *root* directory and then in *api* directory after merging this pull request.
=> Added new methods to organization and project services LMR-195

api/src/main/java/io/lumeer/engine/api/LumeerConst.java, api/src/main/java/io/lumeer/engine/api/dto/UserSettings.java, mongodb-storage/src/main/java/io/lumeer/mongodb/MongoDbStorage.java, war/src/main/java/io/lumeer/engine/controller/DatabaseInitializer.java, war/src/main/java/io/lumeer/engine/controller/UserSettingsFacade.java, war/src/main/java/io/lumeer/engine/rest/UserSettingsService.java, war/src/test/java/io/lumeer/engine/controller/UserSettingsFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/rest/UserSettingsServiceIntegrationTest.java
I'm not sure about scope of `Facade` and also `Service` but i'm too tired to think about it :D
=> Created UserSettingsFacade and Service #LMR-204

api/src/main/java/io/lumeer/engine/api/LumeerConst.java, api/src/main/java/io/lumeer/engine/api/dto/Role.java, war/src/main/java/io/lumeer/engine/controller/SecurityFacade.java, war/src/main/java/io/lumeer/engine/rest/SecurityService.java, war/src/test/java/io/lumeer/engine/controller/SecurityFacadeIntegrationTest.java, war/src/test/java/io/lumeer/engine/rest/SecurityServiceIntegrationTest.java
Tha last pulls had to do something with URLs for my tests. I think there could be conflicts.
I've defined URLs as in the updated comment: https://lumeer.myjetbrains.com/youtrack/issue/LMR-203#comment=100-114
But I temporarily added `/roles` before all of the URLs in the code to pass all the tests.
=> Implementation of the SecurityService #LMR-203

war/src/main/java/io/lumeer/engine/controller/CollectionFacade.java, war/src/main/java/io/lumeer/engine/controller/OrganizationFacade.java, war/src/main/java/io/lumeer/engine/controller/ProjectFacade.java, war/src/main/java/io/lumeer/engine/controller/ViewFacade.java, war/src/test/java/io/lumeer/engine/rest/CollectionServiceIntegrationTest.java, war/src/test/java/io/lumeer/engine/rest/ViewServiceIntegrationTest.java
I have changed the default permissions so the user who created a resource is able to do anything with it by default.
=> Fix resource default permissions #LMR-233

api/pom.xml, bom/pom.xml, mongodb-storage/pom.xml, simple-cache/pom.xml, utils/pom.xml, war/pom.xml
There were unnecessary dependency management sections in our POM files.
=> Improve BOM module dependency usage

lumeer-core/src/main/java/io/lumeer/core/cache/UserCache.java, lumeer-core/src/main/java/io/lumeer/core/model/SimpleUser.java, lumeer-storage/lumeer-storage-api/src/main/java/io/lumeer/storage/api/dao/UserDao.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/dao/organization/MongoUserDao.java, lumeer-storage/lumeer-storage-mongodb/src/test/java/io/lumeer/storage/mongodb/dao/organization/MongoUserDaoTest.java
@martinglova, this should fix that NPE.
=> Create not existing users #LMR-311

pom.xml
Signed-off-by: justmesr <simon.kocurek@gmail.com>
=> Change maven licence

api/src/main/java/io/lumeer/api/model/LinkInstance.java, api/src/main/java/io/lumeer/api/model/LinkType.java, lumeer-core/src/main/java/io/lumeer/core/facade/LinkInstanceFacade.java, lumeer-core/src/main/java/io/lumeer/core/facade/LinkTypeFacade.java, lumeer-remote/src/main/java/io/lumeer/remote/rest/LinkInstanceService.java, lumeer-remote/src/main/java/io/lumeer/remote/rest/LinkTypeService.java, lumeer-storage/lumeer-storage-api/src/main/java/io/lumeer/storage/api/dao/LinkInstanceDao.java, lumeer-storage/lumeer-storage-api/src/main/java/io/lumeer/storage/api/dao/LinkTypeDao.java
@kubedo8, I have prepared interfaces for links. Let me know if you have any questions.
=> Prepare link interfaces #LMR-571

api/src/main/java/io/lumeer/api/dto/JsonCollection.java, api/src/main/java/io/lumeer/api/util/AttributeUtil.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/model/MorphiaCollection.java
It removed all attributes with the same prefix before.
=> Fix removing child attributes #LMR-742

api/src/main/java/io/lumeer/api/model/Feedback.java, lumeer-core/src/main/java/io/lumeer/core/facade/UserFacade.java, lumeer-remote/src/main/java/io/lumeer/remote/rest/GlobalService.java, lumeer-storage/lumeer-storage-api/src/main/java/io/lumeer/storage/api/dao/FeedbackDao.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/MongoDbStorage.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/codecs/FeedbackCodec.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/codecs/providers/FeedbackCodecProvider.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/dao/system/MongoFeedbackDao.java, lumeer-storage/lumeer-storage-mongodb/src/test/java/io/lumeer/storage/mongodb/dao/system/MongoFeedbackDaoTest.java, war/src/test/java/io/lumeer/core/facade/UserFacadeIT.java
I am adding a new REST method which will enable users to leave feedback.
**Merge this together with front-end pull-request!**
=> Add user feedback form #LMR-994

api/src/main/java/io/lumeer/engine/api/data/DataStorage.java, api/src/main/java/io/lumeer/engine/api/data/DataStorageFactory.java, lumeer-core/src/main/java/io/lumeer/core/WorkspaceKeeper.java, lumeer-core/src/main/java/io/lumeer/core/cache/UserCache.java, lumeer-core/src/main/java/io/lumeer/core/cache/WorkspaceCache.java, lumeer-core/src/main/java/io/lumeer/core/facade/PaymentFacade.java, lumeer-core/src/main/java/io/lumeer/core/provider/DataStorageProvider.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/MongoDbStorage.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/MongoDbStorageFactory.java
Change application scoped caches to request scoped, remove rarely used caches, and remove deprecated Mongo Client API
=> Convert application scoped workspace to request scoped

bom/pom.xml, pom.xml, war/pom.xml, war/settings.xml
including embedded MongoDB with a single command
=> Add the possibility to start engine via Maven

api/src/main/java/io/lumeer/api/dto/JsonDocument.java, api/src/main/java/io/lumeer/api/model/Document.java, lumeer-core/src/main/java/io/lumeer/core/facade/DocumentFacade.java, lumeer-remote/src/main/java/io/lumeer/remote/rest/DocumentService.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/model/MorphiaDocument.java, war/src/test/java/io/lumeer/remote/rest/DocumentServiceIT.java
Do not merge yet, tests are missing.
=> Add frontend-editable document meta data #LMR-1138

api/src/main/java/io/lumeer/api/model/geocoding/Address.java, api/src/main/java/io/lumeer/api/model/geocoding/Coordinates.java, api/src/main/java/io/lumeer/api/model/geocoding/Location.java, lumeer-core/src/main/java/io/lumeer/core/cache/GeoCodingCache.java, lumeer-core/src/main/java/io/lumeer/core/client/mapquest/MapQuestClient.java, lumeer-core/src/main/java/io/lumeer/core/client/mapquest/MapQuestLatLng.java, lumeer-core/src/main/java/io/lumeer/core/client/mapquest/MapQuestLocation.java, lumeer-core/src/main/java/io/lumeer/core/client/mapquest/MapQuestProvidedLocation.java, lumeer-core/src/main/java/io/lumeer/core/client/opensearch/OpenSearchAddress.java, lumeer-core/src/main/java/io/lumeer/core/client/opensearch/OpenSearchClient.java, lumeer-core/src/main/java/io/lumeer/core/client/opensearch/OpenSearchResult.java, lumeer-core/src/main/java/io/lumeer/core/facade/GeoCodingFacade.java, lumeer-remote/src/main/java/io/lumeer/remote/rest/GeoCodingService.java
Do not merge without a related pull-request on the frontend side. Otherwise, the application will be broken.
=> Improve geocoding API #LMR-1861

lumeer-core/src/main/java/io/lumeer/core/template/TemplateType.java, lumeer-core/src/main/resources/templates/edcal.cs.json, lumeer-core/src/main/resources/templates/edcal.en.json
=> Add editorial calendar template #LMR-1954

api/src/main/java/io/lumeer/api/model/View.java, lumeer-core/src/main/java/io/lumeer/core/facade/ViewFacade.java, lumeer-remote/src/main/java/io/lumeer/remote/rest/ViewService.java, lumeer-storage/lumeer-storage-api/src/main/java/io/lumeer/storage/api/dao/FavoriteItemDao.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/codecs/ViewCodec.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/dao/organization/MongoFavoriteItemDao.java, lumeer-storage/lumeer-storage-mongodb/src/test/java/io/lumeer/storage/mongodb/dao/organization/MongoFavoriteItemDaoTest.java
=> Add support for favorite views and last time used in views #LMR-1973

lumeer-core/src/main/java/io/lumeer/core/template/TemplateType.java, lumeer-core/src/main/resources/templates/task.cs.json, lumeer-core/src/main/resources/templates/task.en.json
=> Add task tracker template #LMR-1979

lumeer-core/src/main/java/io/lumeer/core/facade/UserFacade.java
=> Fix user invite

lumeer-core/src/main/java/io/lumeer/core/facade/CollectionFacade.java
=> Fix resetting of default attribute

lumeer-core/src/main/resources/templates/work.cs.json, lumeer-core/src/main/resources/templates/work.en.json
=> Update work template #LMR-2049

lumeer-core/src/main/java/io/lumeer/core/template/TemplateParser.java
=> Add temporary println

lumeer-core/src/main/java/io/lumeer/core/auth/HeadersFilter.java, lumeer-core/src/main/java/io/lumeer/core/auth/RequestDataKeeper.java, lumeer-core/src/main/java/io/lumeer/core/facade/detector/AbstractPurposeChangeDetector.java, lumeer-core/src/main/java/io/lumeer/core/task/AbstractContextualTask.java, lumeer-core/src/main/java/io/lumeer/core/task/ContextualTask.java, lumeer-core/src/main/java/io/lumeer/core/task/executor/operation/stage/SingleStage.java
This supports both app id for push notifications as well as document creation correlation id.
=> Add secondary correlation ID

.travis.yml, lumeer-core/src/main/java/io/lumeer/core/auth/Auth0Filter.java, lumeer-core/src/main/java/io/lumeer/core/auth/UserAuth0Utils.java, lumeer-core/src/main/java/io/lumeer/core/facade/UserFacade.java, lumeer-remote/src/main/java/io/lumeer/remote/rest/UserService.java
login, set email as verified, remove user
=> Add several user manipulation endpoints

lumeer-core/src/main/java/io/lumeer/core/auth/UserAuth0Utils.java
This reverts commit 73f70a98b0f23b69fd858d1a26cf4fe595f9c3ab.
=> Revert "fix verify email (#1002)"

api/src/main/java/io/lumeer/api/model/CollectionPurpose.java, api/src/main/java/io/lumeer/api/model/LogEvent.java, api/src/main/java/io/lumeer/engine/api/data/StorageConnection.java, lumeer-core/src/main/java/io/lumeer/core/action/DelayedActionProcessor.java, lumeer-core/src/main/java/io/lumeer/core/auth/AuthenticatedUser.java, lumeer-core/src/main/java/io/lumeer/core/facade/ConfigurationFacade.java, lumeer-core/src/main/java/io/lumeer/core/facade/EventLogFacade.java, lumeer-core/src/main/java/io/lumeer/core/facade/SystemConfigurationFacade.java, lumeer-core/src/main/java/io/lumeer/core/facade/SystemDatabaseConfigurationFacade.java, lumeer-core/src/main/java/io/lumeer/core/facade/UserFacade.java, lumeer-core/src/main/java/io/lumeer/core/facade/configuration/DefaultConfigurationProducer.java, lumeer-core/src/main/kotlin/io/lumeer/core/util/EmailService.kt, lumeer-remote/src/main/java/io/lumeer/remote/rest/UserService.java, lumeer-storage/lumeer-storage-mongodb/src/main/java/io/lumeer/storage/mongodb/MongoDbStorage.java, war/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, war/src/test/java/io/lumeer/core/facade/DelayedActionIT.java
Update mongodb storage configuration, add ability to connect to mongodb+srv, add priority Slack notificaitons, disable emails when no server is configured, sent only one past due date user notification (unless explicitely specified in the collection)
=> Updates to new infrastructure
